
export const apiConstants = {

    API_SUBMISSION:"API_SUBMISSION",
    CREATE_API_REQUEST: 'CREATE_API_REQUEST',
    CREATE_API_SUCCESS: 'CREATE_API_SUCCESS',
    CREATE_API_FAILURE: 'CREATE_API_FAILURE'

}


